=== zdugi/XMLProjekat/doc/schema/obavestenje.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified"
    targetNamespace="http://ftn.uns.ac.rs/xml_obavestenja"
    xmlns:obavestenje="http://ftn.uns.ac.rs/xml_obavestenja">
    <xs:element name="Obavestenje">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="Datum" type="obavestenje:TDatum"/>
                <xs:element name="Organ" type="obavestenje:TOrgan"/>
                <xs:element name="Podaci_podnosioca" type="obavestenje:TPodnosilac"/>
                <xs:element name="Telo_obavestenja" type="obavestenje:TTelo_obavestenja"/>
                <xs:element name="Dostavljeno" type="obavestenje:TDostavljeno"/>
            </xs:sequence>
            <xs:attribute name="Broj_predmeta" type="xs:string"/>
            <xs:attribute name="Naziv" type="xs:string"/>
        </xs:complexType>
    </xs:element>
    <xs:complexType name="TDatum">
        <xs:sequence>
            <xs:element name="Dan" type="xs:gDay"/>
            <xs:element name="Mesec" type="xs:gMonth"/>
            <xs:element name="Godina" type="xs:gYear"/>
        </xs:sequence>
    </xs:complexType>
    <xs:complexType name="TOrgan">
        <xs:sequence>
            <xs:element name="Naziv" type="obavestenje:TOsoba"/>
            <xs:element name="Adresa" type="obavestenje:TAdresa"/>
        </xs:sequence>
    </xs:complexType>
    <xs:complexType name="TAdresa">
        <xs:sequence>
            <xs:element name="Ulica" type="xs:string"/>
            <xs:element name="Broj" type="xs:positiveInteger"/>
            <xs:element name="Postanski_broj" type="xs:positiveInteger"/>
            <xs:element name="Mesto" type="xs:string"/>
            <xs:element name="Drzava" type="xs:string"/>
        </xs:sequence>
    </xs:complexType>
    <xs:complexType mixed="true" name="TTelo_obavestenja">
        <xs:sequence>
            <xs:element name="Zakon" type="xs:string"/>
            <xs:element name="Godina" type="xs:gYear"/>
            <xs:element name="Dan" type="xs:gDay"/>
            <xs:element name="Vreme" type="xs:time"/>
            <xs:element name="Adresa" type="obavestenje:TAdresa"/>
            <xs:element name="Kancelarija" type="xs:positiveInteger"/>
            <xs:element name="Suma" type="xs:double"/>
        </xs:sequence>
    </xs:complexType>
    <xs:complexType name="TPodnosilac">
        <xs:sequence>
            <xs:choice>
                <xs:element name="Osoba" type="obavestenje:TOsoba"/>
                <xs:element name="Naziv" type="xs:string"/>
            </xs:choice>
            <xs:element name="Adresa" type="obavestenje:TAdresa"/>
        </xs:sequence>
    </xs:complexType>
    <xs:complexType name="TOsoba">
        <xs:sequence>
            <xs:element name="Ime" type="xs:string"/>
            <xs:element name="Prezime" type="xs:string"/>
        </xs:sequence>
    </xs:complexType>
    <xs:complexType name="TDostavljeno">
        <xs:attribute default="false" name="Imenovanom" type="xs:boolean"/>
        <xs:attribute default="false" name="Arhivi" type="xs:boolean"/>
    </xs:complexType>
</xs:schema>

=== zdugi/XMLProjekat/doc/xml/obavestenje_original.xml
<?xml version="1.0" encoding="UTF-8"?>
<obavestenje:Obavestenje xmlns:obavestenje="http://ftn.uns.ac.rs/xml_obavestenja"
 xmlns:opste="http://ftn.uns.ac.rs/xml_opste"
 xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
 xsi:schemaLocation="http://ftn.uns.ac.rs/xml_obavestenja file://D:/XML/PROJEKAT/XMLProjekat/doc/obavestenje.xsd"
 Broj_predmeta="123-321" Naziv="OBAVEŠTENjE o stavljanju na uvid dokumenta koji sadrži traženu informaciju i o izradi kopije"
    about = "http://localhost:8081/notification/id">
    <obavestenje:Datum property = "pred:datumObavestenja">
        12.12.2020.
    </obavestenje:Datum>
    <obavestenje:Organ>
        <opste:Naziv property="pred:nazivOrgana">Naziv organa</opste:Naziv>
        <opste:Adresa>
            <opste:Ulica>Milosa Crnjanskog</opste:Ulica>
            <opste:Broj>21</opste:Broj>
            <opste:Postanski_broj>32123</opste:Postanski_broj>
            <opste:Mesto property="pred:mestoOrgana">Novi Sad</opste:Mesto>
            <opste:Drzava property="pred:drzavaOrgana">Srbija</opste:Drzava>
        </opste:Adresa>
    </obavestenje:Organ>
    <obavestenje:Podaci_podnosioca>
        <obavestenje:Naziv property = "pred:nazivPodnosioca">Naziv podnosioca</obavestenje:Naziv>
        <obavestenje:Adresa>
            <opste:Ulica>Ulica0</opste:Ulica>
            <opste:Broj>50</opste:Broj>
            <opste:Postanski_broj>50</opste:Postanski_broj>
            <opste:Mesto property="pred:mestoPodnosioca">Mesto0</opste:Mesto>
            <opste:Drzava property="pred:drzavaPodnosioca">Drzava0</opste:Drzava>
        </obavestenje:Adresa>
    </obavestenje:Podaci_podnosioca>
    <obavestenje:Telo_obavestenja>
        <obavestenje:Zakon>
            <opste:Naziv_zakona>člana 16. st. 1. Zakona o slobodnom pristupu informacijama od javnog značaja</opste:Naziv_zakona>
        </obavestenje:Zakon>
        <obavestenje:Godina>50</obavestenje:Godina>
        god., kojim ste tražili uvid u dokument/e sa informacijama o / u vezi sa:
        <obavestenje:Opis Savet="opis trayene informacije"></obavestenje:Opis>
        obaveštavamo vas da dana <obavestenje:Dan>16</obavestenje:Dan>, u časova <obavestenje:Sati>13</obavestenje:Sati>, odnosno u vremenu od
        <obavestenje:Pocetni_sat>12</obavestenje:Pocetni_sat> do <obavestenje:Zavrsni_sat>18</obavestenje:Zavrsni_sat> časova, u prostorijama organa u <obavestenje:Adresa>
            <opste:Ulica>Ulica1</opste:Ulica>
            <opste:Broj>50</opste:Broj>
            <opste:Postanski_broj>50</opste:Postanski_broj>
            <opste:Mesto property="pred:mestoOrganaObavestenje">Mesto1</opste:Mesto>
            <opste:Drzava property="pred:drzavaOrganaObavestenje">Drzava1</opste:Drzava>
        </obavestenje:Adresa>, kancelarija br. <obavestenje:Kancelarija>50</obavestenje:Kancelarija> možete izvršiti uvid u dokument/e u kome je sadržana tražena informacija.
        Tom prilikom, na vaš zahtev, može vam se izdati i kopija dokumenta sa traženom informacijom.
        Troškovi su utvrđeni Uredbom Vlade Republike Srbije („Sl. glasnik RS“, br. 8/06), i to: kopija strane A4 formata iznosi 3 dinara, A3 formata 6 dinara, CD 35 dinara, diskete 20 dinara, DVD 40 dinara, audio-kaseta – 150 dinara, video-kaseta 300 dinara, pretvaranje jedne strane dokumenta iz fizičkog u elektronski oblik – 30 dinara.
        Iznos ukupnih troškova izrade kopije dokumenta po vašem zahtevu iznosi <obavestenje:Suma>0</obavestenje:Suma> dinara i uplaćuje se na žiro-račun Budžeta Republike Srbije br. 840-742328-843-30, s pozivom na broj 97 – oznaka šifre opštine/grada gde se nalazi organ vlasti (iz Pravilnika o uslovima i načinu vođenja računa – „Sl. glasnik RS“, 20/07... 40/10). 
    </obavestenje:Telo_obavestenja>
    <obavestenje:Dostavljeno Arhivi="true" about = "http://localhost:8081/notification/arhivi"/>
</obavestenje:Obavestenje>

=== zdugi/XMLProjekat/koncept/data/xml/obavestenje1.xml
<?xml version="1.0" encoding="UTF-8"?>
<obavestenje:Obavestenje xmlns:obavestenje="http://ftn.uns.ac.rs/xml_obavestenja"
 xmlns:opste="http://ftn.uns.ac.rs/xml_opste"
 xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
 xsi:schemaLocation="http://ftn.uns.ac.rs/xml_obavestenja file:/C:/Users/Zdravko/Documents/Lab/fax/XMLProjekat/doc/schema/obavestenje.xsd">
    <obavestenje:Datum>
        <opste:Dan>---01</opste:Dan>
        <opste:Mesec>--01</opste:Mesec>
        <opste:Godina>2006</opste:Godina>
    </obavestenje:Datum>
    <obavestenje:Organ>
        <opste:Naziv>
        </opste:Naziv>
        <opste:Adresa>
            <opste:Ulica>Ulica0</opste:Ulica>
            <opste:Broj>50</opste:Broj>
            <opste:Postanski_broj>50</opste:Postanski_broj>
            <opste:Mesto>Mesto0</opste:Mesto>
            <opste:Drzava>Drzava0</opste:Drzava>
        </opste:Adresa>
    </obavestenje:Organ>
    <obavestenje:Podaci_podnosioca>
        <obavestenje:Naziv>Naziv0</obavestenje:Naziv>
        <obavestenje:Adresa>
            <opste:Ulica>Ulica1</opste:Ulica>
            <opste:Broj>50</opste:Broj>
            <opste:Postanski_broj>50</opste:Postanski_broj>
            <opste:Mesto>Mesto1</opste:Mesto>
            <opste:Drzava>Drzava1</opste:Drzava>
        </obavestenje:Adresa>
    </obavestenje:Podaci_podnosioca>
    <obavestenje:Telo_obavestenja>
        <obavestenje:Zakon>Zakon0</obavestenje:Zakon>
        <obavestenje:Godina>2006</obavestenje:Godina>
        <obavestenje:Dan>---01</obavestenje:Dan>
        <obavestenje:Vreme>01:01:01.001</obavestenje:Vreme>
        <obavestenje:Adresa>
            <opste:Ulica>Ulica2</opste:Ulica>
            <opste:Broj>50</opste:Broj>
            <opste:Postanski_broj>50</opste:Postanski_broj>
            <opste:Mesto>Mesto2</opste:Mesto>
            <opste:Drzava>Drzava2</opste:Drzava>
        </obavestenje:Adresa>
        <obavestenje:Kancelarija>50</obavestenje:Kancelarija>
        <obavestenje:Suma>0</obavestenje:Suma>
    </obavestenje:Telo_obavestenja>
    <obavestenje:Dostavljeno/>
</obavestenje:Obavestenje>
